/* prototypes for accessors */

#ifndef _ACCESSORS_H
#define _ACCESSORS_H

int write_char_array(const ubx_port_t *p, const char *val, const int len);
int write_char(const ubx_port_t *p, const char *val);
long read_char_array(const ubx_port_t *p, char *val, const int len);
long read_char(const ubx_port_t *p, char *val);
long cfg_getptr_char(const ubx_block_t *b, const char *cfg_name, const char **valptr);
int write_int_array(const ubx_port_t *p, const int *val, const int len);
int write_int(const ubx_port_t *p, const int *val);
long read_int_array(const ubx_port_t *p, int *val, const int len);
long read_int(const ubx_port_t *p, int *val);
long cfg_getptr_int(const ubx_block_t *b, const char *cfg_name, const int **valptr);
int write_uint_array(const ubx_port_t *p, const unsigned int *val, const int len);
int write_uint(const ubx_port_t *p, const unsigned int *val);
long read_uint_array(const ubx_port_t *p, unsigned int *val, const int len);
long read_uint(const ubx_port_t *p, unsigned int *val);
long cfg_getptr_uint(const ubx_block_t *b, const char *cfg_name, const unsigned int **valptr);
int write_long_array(const ubx_port_t *p, const long *val, const int len);
int write_long(const ubx_port_t *p, const long *val);
long read_long_array(const ubx_port_t *p, long *val, const int len);
long read_long(const ubx_port_t *p, long *val);
long cfg_getptr_long(const ubx_block_t *b, const char *cfg_name, const long **valptr);
int write_ulong_array(const ubx_port_t *p, const unsigned long *val, const int len);
int write_ulong(const ubx_port_t *p, const unsigned long *val);
long read_ulong_array(const ubx_port_t *p, unsigned long *val, const int len);
long read_ulong(const ubx_port_t *p, unsigned long *val);
long cfg_getptr_ulong(const ubx_block_t *b, const char *cfg_name, const unsigned long **valptr);
int write_uint8_array(const ubx_port_t *p, const uint8_t *val, const int len);
int write_uint8(const ubx_port_t *p, const uint8_t *val);
long read_uint8_array(const ubx_port_t *p, uint8_t *val, const int len);
long read_uint8(const ubx_port_t *p, uint8_t *val);
long cfg_getptr_uint8(const ubx_block_t *b, const char *cfg_name, const uint8_t **valptr);
int write_uint16_array(const ubx_port_t *p, const uint16_t *val, const int len);
int write_uint16(const ubx_port_t *p, const uint16_t *val);
long read_uint16_array(const ubx_port_t *p, uint16_t *val, const int len);
long read_uint16(const ubx_port_t *p, uint16_t *val);
long cfg_getptr_uint16(const ubx_block_t *b, const char *cfg_name, const uint16_t **valptr);
int write_uint32_array(const ubx_port_t *p, const uint32_t *val, const int len);
int write_uint32(const ubx_port_t *p, const uint32_t *val);
long read_uint32_array(const ubx_port_t *p, uint32_t *val, const int len);
long read_uint32(const ubx_port_t *p, uint32_t *val);
long cfg_getptr_uint32(const ubx_block_t *b, const char *cfg_name, const uint32_t **valptr);
int write_uint64_array(const ubx_port_t *p, const uint64_t *val, const int len);
int write_uint64(const ubx_port_t *p, const uint64_t *val);
long read_uint64_array(const ubx_port_t *p, uint64_t *val, const int len);
long read_uint64(const ubx_port_t *p, uint64_t *val);
long cfg_getptr_uint64(const ubx_block_t *b, const char *cfg_name, const uint64_t **valptr);
int write_int8_array(const ubx_port_t *p, const int8_t *val, const int len);
int write_int8(const ubx_port_t *p, const int8_t *val);
long read_int8_array(const ubx_port_t *p, int8_t *val, const int len);
long read_int8(const ubx_port_t *p, int8_t *val);
long cfg_getptr_int8(const ubx_block_t *b, const char *cfg_name, const int8_t **valptr);
int write_int16_array(const ubx_port_t *p, const int16_t *val, const int len);
int write_int16(const ubx_port_t *p, const int16_t *val);
long read_int16_array(const ubx_port_t *p, int16_t *val, const int len);
long read_int16(const ubx_port_t *p, int16_t *val);
long cfg_getptr_int16(const ubx_block_t *b, const char *cfg_name, const int16_t **valptr);
int write_int32_array(const ubx_port_t *p, const int32_t *val, const int len);
int write_int32(const ubx_port_t *p, const int32_t *val);
long read_int32_array(const ubx_port_t *p, int32_t *val, const int len);
long read_int32(const ubx_port_t *p, int32_t *val);
long cfg_getptr_int32(const ubx_block_t *b, const char *cfg_name, const int32_t **valptr);
int write_int64_array(const ubx_port_t *p, const int64_t *val, const int len);
int write_int64(const ubx_port_t *p, const int64_t *val);
long read_int64_array(const ubx_port_t *p, int64_t *val, const int len);
long read_int64(const ubx_port_t *p, int64_t *val);
long cfg_getptr_int64(const ubx_block_t *b, const char *cfg_name, const int64_t **valptr);
int write_size_t_array(const ubx_port_t *p, const size_t *val, const int len);
int write_size_t(const ubx_port_t *p, const size_t *val);
long read_size_t_array(const ubx_port_t *p, size_t *val, const int len);
long read_size_t(const ubx_port_t *p, size_t *val);
long cfg_getptr_size_t(const ubx_block_t *b, const char *cfg_name, const size_t **valptr);
int write_float_array(const ubx_port_t *p, const float *val, const int len);
int write_float(const ubx_port_t *p, const float *val);
long read_float_array(const ubx_port_t *p, float *val, const int len);
long read_float(const ubx_port_t *p, float *val);
long cfg_getptr_float(const ubx_block_t *b, const char *cfg_name, const float **valptr);
int write_double_array(const ubx_port_t *p, const double *val, const int len);
int write_double(const ubx_port_t *p, const double *val);
long read_double_array(const ubx_port_t *p, double *val, const int len);
long read_double(const ubx_port_t *p, double *val);
long cfg_getptr_double(const ubx_block_t *b, const char *cfg_name, const double **valptr);

#endif /* _ACCESSORS_H */
