
enum {
	/* Motor control modes */
	YOUBOT_CMODE_MOTORSTOP =			0,
	YOUBOT_CMODE_POSITIONING =			1,
	YOUBOT_CMODE_VELOCITY =				2,
	YOUBOT_CMODE_NOACTION =				3,
	YOUBOT_CMODE_SET_POSITION_TO_REFERENCE = 	4,
	YOUBOT_CMODE_PWM =				5,
	YOUBOT_CMODE_CURRENT = 				6,
	YOUBOT_CMODE_INITIALIZE = 			7,
};
